base_config: 'configs/attend_similarity/base.yml'


teacher_model:
  name: 'attend_similarity_teacher'
  params:
    scale: 2
    n_colors: 1


student_model:
  name: 'attend_similarity_student'
  params:
    scale: 2
    n_colors: 1
    modules_to_freeze:
      - 'expanding'
      - 'mapping2'
      - 'expanding2'
    initialize_from: 'results/attend_similarity/attend_similarity_teacher/checkpoint/'
    modules_to_initialize:
      - 'expanding'
      - 'mapping2'
      - 'expanding2'


train:
  batch_size: 32
  num_epochs: 1000
  teacher_dir: ''
  student_dir: '.distill_mapping.scratch'


eval:
  batch_size: 1


scheduler:
  name: 'none'


optimizer:
  name: adam
  params:
    lr: 0.001


loss:
  name: 'distillation_loss'
  params:
    reduction: 'mean'
    standardization: False
    lambda1: 1.0
    lambda2: 1.0
    distill:
    # - 'teacher_layer_name:student_layer_name:weight'
      - 'mapping:mapping:1'


visualizer:
  name: 'step2'


gpu: 1


