<<<<<<< HEAD
base_config: 'configs/noisy_teacher/base.yml'


teacher_model:
  name: 'noisy_teacher'
  params:
    scale: 2
    n_colors: 1


student_model:
  name: 'attend_similarity_student'
  params:
    scale: 2
    n_colors: 1
    modules_to_freeze:
      - 'expanding'
      - 'mapping2'
      - 'expanding2'
    initialize_from: 'results/noisy_teacher/noisy_teacher.noisy_teacher.from.distill_mapping.nogt/checkpoint/'
    modules_to_initialize:
      - 'feature_extraction'
      - 'shirinking'
      - 'mapping'
      - 'expanding'
      - 'mapping2'
      - 'expanding2'


train:
  batch_size: 32
  num_epochs: 1000
  teacher_dir: '.noisy_teacher.from.distill_mapping.nogt'
  student_dir: '.from_noisy_teacher.noise_offset10.lambda1e-2'


eval:
  batch_size: 1


scheduler:
  name: 'none'


optimizer:
  name: adam
  params:
    lr: 0.001


loss:
  name: 'attend_similarity_loss'
  params:
    reduction: 'mean'
    reverse: True
    standardize: False
    lambda1: 1
    lambda2: 0.01
    lambda3: 0
    attend:
      - 'mapping:mapping:1'


visualizer:
  name: 'step2'


gpu: 0

||||||| merged common ancestors
=======
base_config: 'configs/noisy_teacher/base.yml'


teacher_model:
  name: 'noisy_teacher'
  params:
    scale: 2
    n_colors: 1


student_model:
  name: 'attend_similarity_student'
  params:
    scale: 2
    n_colors: 1
    modules_to_freeze:
      - 'expanding'
      - 'mapping2'
      - 'expanding2'
    initialize_from: 
      - 'results/attend_similarity/attend_similarity_student.distill_mapping.nogt.l1/checkpoint/'
      - 'results/noisy_teacher/noisy_teacher.noisy_teacher.from.distill_mapping.nogt.l1/checkpoint/'
    modules_to_initialize:
      - - 'feature_extraction'
        - 'shirinking'
        - 'mapping'
      - - 'expanding'
        - 'mapping2'
        - 'expanding2'


train:
  batch_size: 32
  num_epochs: 1000
  teacher_dir: '.noisy_teacher.from.distill_mapping.nogt.l1'
  student_dir: '.from_noisy_teacher.cossim'


eval:
  batch_size: 1


scheduler:
  name: 'none'


optimizer:
  name: adam
  params:
    lr: 0.001


loss:
  name: 'attend_similarity_loss'
  params:
    reduction: 'mean'
    reverse: True
    standardize: False
    lambda1: 1
    lambda2: 0.01
    lambda3: 0
    attend:
      - 'mapping:mapping:1'


visualizer:
  name: 'step2'


gpu: 0

>>>>>>> master
