base_config: 'configs/noisy_teacher/base.yml'


student_model:
  name: 'attend_similarity_student'
  params:
    scale: 2
    n_colors: 1


train:
  batch_size: 32
  num_epochs: 1000
  student_dir: '.base'
  fine_tune: False


eval:
  batch_size: 1


scheduler:
  name: 'none'


optimizer:
  name: adam
  params:
    lr: 0.0001
 
 
loss:
  name: 'l1loss'
  params:
    reduction: 'mean'


visualizer:
  name: 'step0'


gpu: 0

