base_config: 'configs/disentangle_resolution/base.yml'


teacher_model:
  name: 'disentangle_teacher'
  params:
    scale: 2
    n_colors: 1


student_model:
  name: 'disentangle_student'
  params:
    scale: 2
    n_colors: 1
    m_1 : 12
    modules_to_freeze:
      - 'expanding'
      - 'mapping2'
      - 'expanding2'
    # initialize_from: 'results/attend_similarity/attend_similarity_student.distill_mapping/checkpoint/'
    # modules_to_initialize:
    #   - 'expanding'
    #   - 'mapping2'
    #   - 'expanding2'


train:
  batch_size: 32
  num_epochs: 1000
  teacher_dir: ''
  student_dir: '.large_student'
  fine_tune: False


eval:
  batch_size: 1


scheduler:
  name: 'none'


optimizer:
  name: adam
  params:
    lr: 0.0001


loss:
  name: 'attend_similarity_loss'
  params:
    reduction: 'mean'
    lambda1: 1
    lambda2: 100
    lambda3: 10


visualizer:
  name: 'step2'


gpu: 1

