base_config: 'configs/disentangle_resolution.distill_all/base.yml'


teacher_model:
  name: 'disentangle_teacher'
  params:
    scale: 2
    n_colors: 1


student_model:
  name: 'disentangle_student'
  params:
    scale: 2
    n_colors: 1
    # modules_to_freeze:
     #  - feature_extraction
     #  - mapping
    initialize_from: 'results/disentangle_resolution.distill_all/disentangle_student.base/checkpoint/'
    modules_to_initialize:
      - feature_extraction
      - shirinking
      - mapping
      - expanding
      - mapping2
      - expanding2

train:
  batch_size: 32
  num_epochs: 1000 
  teacher_dir: ''
  student_dir: ''
  fine_tune: False


eval:
  batch_size: 1


scheduler:
  name: 'none'


optimizer:
  name: adam
  params:
    lr: 0.001
 

loss:
  name: 'distillation_loss'
  params:
    reduction: 'mean'
    distill:
    # - 'teacher_layer_name:student_layer_name:weight'
      - 'feature_extraction:feature_extraction:1'
      - 'shirinking:shirinking:1'
      - 'mapping:mapping:1'
      - 'expanding:expanding:1'
      - 'mapping2:mapping2:1'
      - 'expanding2:expanding2:1'
      - 'residual_hr:residual_hr:1'
      

visualizer:
  name: 'step2'


gpu: 2

