base_config: 'configs/metric_learning/base.yml'


student_model:
  name: 'fsrcnn_student'
  params:
    scale: 2
    n_colors: 1
    initialize_from:
      - 'results/metric_learning/mappingfsrcnn_teacher.hard/checkpoint/'
    modules_to_initialize:
      - - 'feature_extraction'
        - 'shrinking'
        - 'mapping'
    modules_to_freeze:
      - 'feature_extraction'
      - 'shrinking'
      - 'mapping'



train:
  batch_size: 32
  num_epochs: 1000
  student_dir: '.from_metric'


eval:
  batch_size: 1


scheduler:
  name: 'none'


optimizer:
  name: adam
  params:
    lr: 0.001


loss:
  name: 'l1loss'
  params:
    reduction: 'mean'


visualizer:
  name: 'step0'


gpu: 0

