data:
  scale: 2
  n_colors: 1
  rgb_range: 1
  num_workers: 3
  train:
    - name: 'DIV2K'
      params:
        base_dir: './data/DIV2K'
        augment: True
        patch_size: 192
        data_range: '1-5'
        test_every: 500

  valid:
    - name: 'DIV2K'
      params:
        base_dir: './data/DIV2K'
        augment: False
        patch_size: 192
        data_range: '1-10'

  test:
    - name: 'Set5'
      params:
        base_dir: './data/benchmark/Set5'
#     - name: 'Set14'
#       params:
#         base_dir: './data/benchmark/Set14'


train:
  dir: './results/train_valid_same/'

