base_config: 'configs/train_valid_same/base.range1-5.yml'


student_model:
  name: 'fsrcnn_student'
  params:
    scale: 2
    n_colors: 1
    s: 60


train:
  batch_size: 32
  num_epochs: 1000
  student_dir: '.base.range1-5'


eval:
  batch_size: 1


scheduler:
  name: 'none'


optimizer:
  name: adam
  params:
    lr: 0.001


loss:
  name: 'l1loss'
  params:
    reduction: 'mean'


visualizer:
  name: 'step0'


gpu: 3

