data:
  scale: 2
  n_colors: 1
  rgb_range: 1
  num_workers: 3
  base_dir: './data/LargeDiffDIV2K'
  train:
    name: 'LargeDiffDIV2K'
    params:
      data_type: 'mix'
  valid:
    name: 'LargeDiffDIV2K'
    params:
      data_type: 'mix'
  test:
    name: ''


train:
  dir: './results/largediff/'

