base_config: 'configs/diff_metric_learning/base.yml'


student_model:
  name: 'fsrcnn_student'
  params:
    scale: 2
    n_colors: 1
    s: 60


train:
  batch_size: 32
  num_epochs: 1000
  student_dir: '.s60.margin'


eval:
  batch_size: 1


scheduler:
  name: 'none'




optimizer:
  name: adam
  params:
    lr: 0.001
    weight_decay: 0.00001


loss:
  name: 'diff_metric_margin_loss'
  params:
    reduction: 'mean'
    lambda1: 1.0
    lambda2: 0.1


visualizer:
  name: 'step0'


gpu: 0

