base_config: 'configs/small_dataset/base.yml'


teacher_model:
  name: 'gt_noisy_teacher'
  params:
    scale: 2
    n_colors: 1
    noise_offset: 100
    # initialize_from: 'results/noisy_teacher/noisy_teacher/checkpoint/'
    # modules_to_initialize:
    #   - 'feature_extraction'
    # - 'shrinking'
    #  - 'mapping'
    #  - 'expanding'
    # modules_to_freeze:
    #  - 'feature_extraction'
    #  - 'shirinking'
    #  - 'mapping'
    layers_to_attend:
      - 'mapping'

train:
  batch_size: 32
  num_epochs: 1000
  teacher_dir: '.noisy_teacher.gt.offset100.weight_decay1e-3'
  student_dir: ''

eval:
  batch_size: 1


scheduler:
  name: 'none'


optimizer:
  name: adam
  params:
    lr: 0.001
    weight_decay: 0.00001


loss:
  name: 'l1loss'
  params:
    reduction: 'mean'

visualizer:
  name: 'step2'


gpu: 1

