base_config: 'configs/small_dataset/base.yml'


teacher_model:
  name: 'gt_noisy_teacher'
  params:
    scale: 2
    n_colors: 1
    noise_offset: 10
    # initialize_from: 'results/noisy_teacher/noisy_teacher/checkpoint/'
    # modules_to_initialize:
    #   - 'feature_extraction'
    # - 'shrinking'
    #  - 'mapping'
    #  - 'expanding'
    # modules_to_freeze:
    #  - 'feature_extraction'
    #  - 'shirinking'
    #  - 'mapping'
    layers_to_attend:
      - 'feature_extraction'
      - 'shrinking'
      - 'mapping'
      - 'expanding'



student_model:
  name: 'fsrcnn_student'
  params:
    scale: 2
    n_colors: 1
    modules_to_freeze:
      - 'feature_extraction'
      - 'shrinking'
      - 'mapping'
      - 'expanding'
    initialize_from:
      - 'results/small_data/fsrcnn_student.distill_mapping/checkpoint/'
    modules_to_initialize:
      - - 'feature_extraction'
        - 'shrinking'
        - 'mapping'
        - 'expanding'
        - 'last_layer'


train:
  batch_size: 32
  num_epochs: 1000
  teacher_dir: '.noisy_teacher.gt.all_layer'
  student_dir: '.distill_mapping'


eval:
  batch_size: 1


scheduler:
  name: 'none'


optimizer:
  name: adam
  params:
    lr: 0.001


loss:
  name: 'l1loss'
  params:
    reduction: 'mean'

visualizer:
  name: 'step2'


gpu: 0

